CREATE TABLE [dbo].[Student]
(
	[StudentId] TINYINT NOT NULL PRIMARY KEY NONCLUSTERED IDENTITY, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [Age] INT NOT NULL, 
    [CreateDate] DATETIME NOT NULL, 
    [UpdateDate] DATETIME NULL 
)
